name: build
on:
  - workflow_call
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make executable
        run: chmod +x ./*.sh
      - name: Build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./*.zip
